foreground   #c7c1cd
background   #0f131b
cursor       #c7c1cd

color0       #0f131b
color8       #8b878f
color1       #57627A
color9       #57627A
color2       #9E6575
color10      #9E6575
color3       #5B7291
color11      #5B7291
color4       #977891
color12      #977891
color5       #6C8FAE
color13      #6C8FAE
color6       #7CACC3
color14      #7CACC3
color7       #c7c1cd
color15      #c7c1cd
