foreground  #dde4e3
background  #0e1514
cursor      #dde4e3

color0      #090f0f
color1      #ffb4ab
color2      #80d5d2
color3      #b2c8e8
color4      #b0ccca
color5      #00504e
color6      #324b4a
color7      #dde4e3
color8      #252b2b
color9      #93000a
color10     #9cf1ee
color11     #cce8e6
color12     #d2e4ff
color13     #80d5d2
color14     #b0ccca
color15     #bec9c7
