[config]
reload_apps = true

[templates.tmux]
input_path = '~/.config/matugen/templates/colors-tmux.conf'
output_path = '~/dotfiles/tmux/colors-tmux.conf'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc'
output_path = '~/.config/dunst/dunstrc'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/colors-kitty.conf'
output_path = '~/.config/kitty/colors-kitty.conf'

[templates.telegram]
input_path = '~/.config/matugen/templates/telegram.tdesktop-theme'
output_path = '~/.cache/wal/telegram.tdesktop-theme'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.cache/wal/colors.json'

[templates.zsh]
input_path = '~/.config/matugen/templates/colors.sh'
output_path = '~/.cache/wal/colors.sh'

[templates.sequences]
input_path = '~/.config/matugen/templates/sequences'
output_path = '~/.cache/wal/sequences'
