 
preload = /home/henrique/dotfiles/Pictures/Wallpapers/gruvbox/a_fish_swimming_in_water.png
wallpaper = , /home/henrique/dotfiles/Pictures/Wallpapers/gruvbox/a_fish_swimming_in_water.png
splash = false
