# See https://wiki.hypr.land/Configuring/Keywords/

################
### MONITORS ###
################
# See https://wiki.hypr.land/Configuring/Monitors/
source = ./monitors.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################
# See https://wiki.hypr.land/Configuring/Environment-variables/
source = ./env.conf

###################
### PERMISSIONS ###
###################
# See https://wiki.hypr.land/Configuring/Permissions/
source = ./permissions.conf


#####################
### LOOK AND FEEL ###
#####################
# Refer to https://wiki.hypr.land/Configuring/Variables/
source = ./style.conf

#############
### INPUT ###
#############
source = ./input.conf

###################
### KEYBINDINGS ###
###################
source = ./keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################
# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules
source = ./rules.conf

#################
### AUTOSTART ###
#################

exec-once = nm-applet &
exec-once = waybar & hyprpaper  



