 
preload = /home/henrique/dotfiles/Pictures/Wallpapers/gruvbox/a_skull_with_spikes_on_it.jpg
wallpaper = , /home/henrique/dotfiles/Pictures/Wallpapers/gruvbox/a_skull_with_spikes_on_it.jpg
splash = false
