 
preload = /home/henrique/dotfiles/Pictures/Wallpapers/gruvbox/a_cat_mask_with_gold_and_blue_accents.jpg
wallpaper = , /home/henrique/dotfiles/Pictures/Wallpapers/gruvbox/a_cat_mask_with_gold_and_blue_accents.jpg
splash = false
