input {
    kb_layout = us, br
    kb_variant = intl,
    kb_options = grp:win_space_toggle,lv3:caps_switch

    follow_mouse = 1

    sensitivity = 0  # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = logitech-usb-receiver-mouse
    sensitivity = -0.5
}

device {
    name = opentabletdriver-virtual-artist-tablet
    output = DP-2
}
