input {
    kb_layout = us, br
    kb_variant = intl,
    kb_options = grp:win_space_toggle

    follow_mouse = 1

    sensitivity = -1 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = logitech-usb-receiver-mouse
    sensitivity = -0.5
}


