# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

windowrule = match:class org.pulseaudio.pavucontrol, float true
#windowrule = float,class:^(google-chrome)$,title:^(Fazer login nas Contas do Google - Google Chrome)$

# Ignore maximize requests from apps. You'll probably like this.
#windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0



